// Builds the Veri-Gate Android app from this repository, and proves what it built.
//
// Why this file exists: the Android project used to be built in a copy under %TEMP%. On 2026-09-19
// Windows' own disk cleanup deleted most of it - half of node_modules and nearly every Android
// resource - and the build stopped working with a hundred errors that looked like a code fault and
// were not. A build that lives where Windows is allowed to delete is not a build you can put in
// front of a client, so this script refuses to work in such a place.
//
// The repository is the source of truth: android/ is committed, including the icons. Nothing here
// is generated by hand. The workspace can be deleted at any time and rebuilt from this script.
//
// Usage:
//   node tools/build-apk.mjs                  build, verify, and write the APK
//   node tools/build-apk.mjs --verify-only    check an existing APK against this tree
//   node tools/build-apk.mjs --clean          throw the workspace away and build from nothing
//
//   --workspace <dir>   where to build   (default: C:\VeriGate\android-build)
//   --out <file>        where to put it  (default: <workspace>/../out/Veri-Gate-V0.8.apk)

import { execFileSync, execSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

// The seven files that are the application. Everything else in the APK is scaffolding.
const WEB_FILES = ["app.js", "cloud.js", "index.html", "styles.css", "service-worker.js", "manifest.webmanifest", "icon.svg"];

// If any of these is missing, node_modules is damaged even though the folder is there. That is
// exactly how the cleanup showed up: npm said everything was installed and the compiler disagreed.
const NODE_SENTINELS = [
  "@capacitor/android/capacitor/src/main/java/com/getcapacitor/Bridge.java",
  "@capacitor/android/capacitor/src/main/java/com/getcapacitor/Plugin.java",
  "@capacitor/android/capacitor/build.gradle",
  "@capacitor/cli/bin/capacitor",
  "@capacitor/core/package.json"
];

// Android resources the manifest names. Their loss is what produced "resource not found" errors.
const ANDROID_SENTINELS = [
  "app/src/main/AndroidManifest.xml",
  "app/src/main/java/com/verigate/gateops/MainActivity.java",
  "app/src/main/res/values/strings.xml",
  "app/src/main/res/values/styles.xml",
  "app/src/main/res/xml/file_paths.xml",
  "app/src/main/res/mipmap-xxxhdpi/ic_launcher.png",
  "gradlew.bat",
  "gradle/wrapper/gradle-wrapper.jar"
];

const args = process.argv.slice(2);
const flag = (name) => args.includes(name);
const option = (name, fallback) => {
  const at = args.indexOf(name);
  return at >= 0 && args[at + 1] ? args[at + 1] : fallback;
};

const workspace = path.resolve(option("--workspace", process.env.VERIGATE_BUILD_DIR || "C:\\VeriGate\\android-build"));
const outFile = path.resolve(option("--out", path.join(path.dirname(workspace), "out", "Veri-Gate-V0.8.apk")));

const say = (message) => console.log(message);
const step = (message) => console.log(`\n== ${message}`);
const fail = (message) => { console.error(`\nSTOPPED: ${message}`); process.exit(1); };

// --- the guard this script exists for -------------------------------------------------------------

// Windows' Storage Sense empties %TEMP%; OneDrive moves files out from under a build and can hand
// back a placeholder instead of the file. Neither is a place to build something a client depends on.
function assertDurable(dir) {
  const target = path.resolve(dir).toLowerCase();
  const forbidden = [
    [path.resolve(os.tmpdir()).toLowerCase(), "the Windows temp folder, which Windows empties on its own"],
    [(process.env.TEMP || "").toLowerCase(), "the Windows temp folder, which Windows empties on its own"],
    [(process.env.TMP || "").toLowerCase(), "the Windows temp folder, which Windows empties on its own"],
    [(process.env.OneDrive || "").toLowerCase(), "OneDrive, which syncs and can replace a file with a placeholder mid-build"],
    [(process.env.OneDriveCommercial || "").toLowerCase(), "OneDrive, which syncs and can replace a file with a placeholder mid-build"],
    [path.join(os.homedir(), "Downloads").toLowerCase(), "the Downloads folder, which Windows also offers to empty"]
  ];
  for (const [prefix, why] of forbidden) {
    if (prefix && (target === prefix || target.startsWith(prefix + path.sep))) {
      fail(`the build workspace is inside ${why}.\n         Asked for: ${dir}\n         Pick somewhere permanent, for example C:\\VeriGate\\android-build.`);
    }
  }
}

function options(cwd, env) {
  return {
    cwd,
    env: { ...process.env, ...env },
    stdio: ["ignore", "pipe", "pipe"],
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024
  };
}

function run(command, commandArgs, cwd, env = {}) {
  return execFileSync(command, commandArgs, options(cwd, env));
}

// Node 24 refuses to spawn a .cmd or .bat directly (EINVAL), so those go through cmd. Each part is
// quoted, because these paths contain spaces, and no more than that: execSync wraps the line in one
// more pair of its own, and cmd /s strips exactly that pair. Adding another breaks the command.
// The batch file is always given its full path - a bare name makes %~dp0 come back as the current
// directory, which is what sent npm looking for its own code inside the workspace.
function runBatch(batch, batchArgs, cwd, env = {}) {
  if (!fs.existsSync(batch)) fail(`missing ${batch}`);
  if (!path.isAbsolute(batch)) fail(`${batch} must be given as a full path`);
  const line = [batch, ...batchArgs].map((part) => `"${part}"`).join(" ");
  return execSync(line, { ...options(cwd, env), shell: process.env.ComSpec || "cmd.exe" });
}

// npm.cmd and npx.cmd work out where they live from %~dp0, and when cmd invokes them through a
// quoted PATH lookup that comes back as the current directory - so npm went looking for its own
// code under the workspace and could not find it. Their scripts are run with this Node directly,
// which has no such problem and no shell in the way.
function nodeScript(name) {
  const script = path.join(path.dirname(process.execPath), "node_modules", "npm", "bin", name);
  if (!fs.existsSync(script)) fail(`cannot find ${name} beside ${process.execPath}. Is Node installed normally?`);
  return script;
}

function runNpm(npmArgs, cwd, env = {}) {
  return run(process.execPath, [nodeScript("npm-cli.js"), ...npmArgs], cwd, env);
}

function runNpx(npxArgs, cwd, env = {}) {
  return run(process.execPath, [nodeScript("npx-cli.js"), ...npxArgs], cwd, env);
}

function copyInto(from, to, { skip = () => false } = {}) {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.cpSync(from, to, { recursive: true, filter: (source) => !skip(source) });
}

function missing(base, names) {
  return names.filter((name) => !fs.existsSync(path.join(base, name)));
}

// --- finding the tools ----------------------------------------------------------------------------

function findJavaHome() {
  if (process.env.JAVA_HOME && fs.existsSync(path.join(process.env.JAVA_HOME, "bin", "java.exe"))) return process.env.JAVA_HOME;
  const candidates = [
    "C:\\Program Files\\Android\\Android Studio\\jbr",
    path.join(process.env.LOCALAPPDATA || "", "Programs", "Android Studio", "jbr"),
    "C:\\Program Files\\Android\\Android Studio\\jre"
  ];
  const found = candidates.find((dir) => dir && fs.existsSync(path.join(dir, "bin", "java.exe")));
  if (!found) fail("no Java found. Android Studio ships one; install it, or set JAVA_HOME.");
  return found;
}

function findAndroidSdk() {
  const candidates = [
    process.env.ANDROID_SDK_ROOT,
    process.env.ANDROID_HOME,
    path.join(process.env.LOCALAPPDATA || "", "Android", "Sdk")
  ];
  const found = candidates.find((dir) => dir && fs.existsSync(path.join(dir, "platform-tools")));
  if (!found) fail("no Android SDK found. Install it through Android Studio, or set ANDROID_SDK_ROOT.");
  return found;
}

function findBuildTools(sdk) {
  const dir = path.join(sdk, "build-tools");
  if (!fs.existsSync(dir)) fail(`no build-tools under ${dir}.`);
  // Highest version wins, compared as numbers so 36 beats 9.
  const newest = fs.readdirSync(dir)
    .filter((name) => /^\d+\./.test(name))
    .sort((a, b) => {
      const pa = a.split(".").map(Number);
      const pb = b.split(".").map(Number);
      for (let i = 0; i < 3; i += 1) if ((pa[i] || 0) !== (pb[i] || 0)) return (pa[i] || 0) - (pb[i] || 0);
      return 0;
    })
    .pop();
  if (!newest) fail(`no build-tools version under ${dir}.`);
  return path.join(dir, newest);
}

// --- preparing the workspace ----------------------------------------------------------------------

function prepare() {
  if (flag("--clean") && fs.existsSync(workspace)) {
    step(`throwing away ${workspace}`);
    fs.rmSync(workspace, { recursive: true, force: true });
  }
  fs.mkdirSync(workspace, { recursive: true });

  step("copying this repository's Android project into the workspace");
  // Never copy build output or a previous machine's SDK path; those are the workspace's own.
  copyInto(path.join(root, "android"), path.join(workspace, "android"), {
    skip: (source) => /[\\/](build|\.gradle)([\\/]|$)/.test(source.slice(root.length)) || source.endsWith("local.properties")
  });
  for (const file of ["capacitor.config.json", "package.json"]) {
    fs.copyFileSync(path.join(root, file), path.join(workspace, file));
  }
  const lock = path.join(root, "package-lock.json");
  if (fs.existsSync(lock)) fs.copyFileSync(lock, path.join(workspace, "package-lock.json"));

  const gone = missing(path.join(workspace, "android"), ANDROID_SENTINELS);
  if (gone.length) fail(`this repository's android/ folder is incomplete. Missing:\n         ${gone.join("\n         ")}`);
  say(`   android/ complete (${ANDROID_SENTINELS.length} checked)`);

  step("copying the seven web files");
  const www = path.join(workspace, "www");
  fs.mkdirSync(www, { recursive: true });
  for (const file of WEB_FILES) fs.copyFileSync(path.join(root, file), path.join(www, file));
  say(`   ${WEB_FILES.join(", ")}`);
}

function installDependencies() {
  const modules = path.join(workspace, "node_modules");
  const damaged = missing(modules, NODE_SENTINELS);
  if (!damaged.length) {
    say("   node_modules intact");
    return;
  }
  if (fs.existsSync(modules)) {
    // npm trusts its own bookkeeping, so a half-deleted package looks installed to it. Remove the
    // package outright and let npm put it back; this is what the cleanup damage needed.
    say(`   node_modules damaged (${damaged.length} file(s) missing) - reinstalling`);
    fs.rmSync(path.join(modules, "@capacitor"), { recursive: true, force: true });
  }
  runNpm(["install", "--no-audit", "--no-fund"], workspace);
  const stillGone = missing(modules, NODE_SENTINELS);
  if (stillGone.length) fail(`npm install did not restore:\n         ${stillGone.join("\n         ")}`);
  say("   node_modules restored");
}

// --- the build ------------------------------------------------------------------------------------

function build(javaHome, sdk) {
  step("checking the build dependencies");
  installDependencies();

  fs.writeFileSync(path.join(workspace, "android", "local.properties"), `sdk.dir=${sdk.replace(/\\/g, "/")}\n`);

  step("capacitor sync (web files into the app, plugins wired up)");
  runNpx(["cap", "sync", "android"], workspace, { JAVA_HOME: javaHome });
  say("   synced");

  step("gradle assembleDebug");
  const gradle = path.join(workspace, "android", "gradlew.bat");
  runBatch(gradle, ["assembleDebug", "--console=plain"], path.join(workspace, "android"), { JAVA_HOME: javaHome });
  const built = path.join(workspace, "android", "app", "build", "outputs", "apk", "debug", "app-debug.apk");
  if (!fs.existsSync(built)) fail("gradle reported success but produced no APK.");
  say(`   built ${(fs.statSync(built).size / 1048576).toFixed(1)} MB`);
  return built;
}

// --- proving what was built -----------------------------------------------------------------------

function verify(apk, javaHome, buildTools) {
  step("verifying the APK against this tree");
  const unpacked = path.join(workspace, "verify");
  fs.rmSync(unpacked, { recursive: true, force: true });
  fs.mkdirSync(unpacked, { recursive: true });

  // Read the seven files straight out of the archive rather than trusting the build.
  const script = `
    const fs = require("fs"), zlib = require("zlib");
    const buf = fs.readFileSync(process.argv[2]);
    const want = new Set(JSON.parse(process.argv[3]).map((n) => "assets/public/" + n));
    const out = {};
    // Walk the central directory backwards from the end-of-central-directory record.
    let eocd = buf.length - 22;
    while (eocd >= 0 && buf.readUInt32LE(eocd) !== 0x06054b50) eocd -= 1;
    if (eocd < 0) { console.log("{}"); process.exit(0); }
    let at = buf.readUInt32LE(eocd + 16);
    const count = buf.readUInt16LE(eocd + 10);
    for (let i = 0; i < count; i += 1) {
      const nameLen = buf.readUInt16LE(at + 28), extraLen = buf.readUInt16LE(at + 30), commentLen = buf.readUInt16LE(at + 32);
      const name = buf.toString("utf8", at + 46, at + 46 + nameLen);
      const method = buf.readUInt16LE(at + 10), size = buf.readUInt32LE(at + 20), offset = buf.readUInt32LE(at + 42);
      if (want.has(name)) {
        const lnLen = buf.readUInt16LE(offset + 26), leLen = buf.readUInt16LE(offset + 28);
        const start = offset + 30 + lnLen + leLen;
        const raw = buf.subarray(start, start + size);
        out[name] = (method === 0 ? raw : zlib.inflateRawSync(raw)).toString("base64");
      }
      at += 46 + nameLen + extraLen + commentLen;
    }
    console.log(JSON.stringify(out));
  `;
  const scriptFile = path.join(unpacked, "read-entries.cjs");
  fs.writeFileSync(scriptFile, script);
  const entries = JSON.parse(run(process.execPath, [scriptFile, apk, JSON.stringify(WEB_FILES)], workspace));

  let mismatched = 0;
  for (const file of WEB_FILES) {
    const inside = entries[`assets/public/${file}`];
    if (!inside) { say(`   MISSING    ${file}`); mismatched += 1; continue; }
    const same = Buffer.from(inside, "base64").equals(fs.readFileSync(path.join(root, file)));
    say(`   ${same ? "identical " : "DIFFERS   "} ${file}`);
    if (!same) mismatched += 1;
  }
  if (mismatched) fail(`${mismatched} of the seven web files in the APK do not match this tree.`);

  // The keyboard fix lives in the compiled manifest, not in the source we copied.
  const tree = run(path.join(buildTools, "aapt2.exe"), ["dump", "xmltree", apk, "--file", "AndroidManifest.xml"], workspace);
  const soft = /windowSoftInputMode\(0x[0-9a-f]+\)=0x([0-9a-f]+)/i.exec(tree);
  if (!soft || (parseInt(soft[1], 16) & 0xf0) !== 0x10) {
    fail("the compiled manifest does not carry adjustResize - the keyboard would cover what the operator types.");
  }
  say("   adjustResize present in the compiled manifest");

  const signed = runBatch(path.join(buildTools, "apksigner.bat"), ["verify", "--verbose", apk], workspace, { JAVA_HOME: javaHome });
  const schemes = ["v1 scheme (JAR signing): true", "v2 scheme (APK Signature Scheme v2): true"];
  for (const scheme of schemes) if (!signed.includes(scheme)) fail(`the APK is not signed: missing ${scheme}`);
  say("   signature valid (v1 and v2)");
}

// --- go -------------------------------------------------------------------------------------------

assertDurable(workspace);
say(`Veri-Gate Android build`);
say(`  repository: ${root}`);
say(`  workspace:  ${workspace}`);
say(`  output:     ${outFile}`);

const javaHome = findJavaHome();
const sdk = findAndroidSdk();
const buildTools = findBuildTools(sdk);
say(`  java:       ${javaHome}`);
say(`  sdk:        ${sdk}`);
say(`  buildtools: ${path.basename(buildTools)}`);

if (flag("--verify-only")) {
  if (!fs.existsSync(outFile)) fail(`no APK at ${outFile}`);
  fs.mkdirSync(workspace, { recursive: true });
  verify(outFile, javaHome, buildTools);
  say(`\nThe APK at ${outFile} matches this tree.`);
  process.exit(0);
}

prepare();
const built = build(javaHome, sdk);
verify(built, javaHome, buildTools);

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.copyFileSync(built, outFile);
say(`\nDone. ${outFile} (${(fs.statSync(outFile).size / 1048576).toFixed(1)} MB)`);
say("Every one of the seven web files in it is byte-identical to this tree.");
